name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set up MariaDB service
        uses: docker://mariadb:latest
        with:
          ports: 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: glass_inventory_management
          MYSQL_USER: ${{ secrets.DB_GLASS_INVENTORY_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_GLASS_INVENTORY_PASSWORD }}

      - name: Set environment variables
        run: |
          echo "DB_GLASS_INVENTORY_USERNAME=${{ secrets.DB_GLASS_INVENTORY_USERNAME }}" >> $GITHUB_ENV
          echo "DB_GLASS_INVENTORY_PASSWORD=${{ secrets.DB_GLASS_INVENTORY_PASSWORD }}" >> $GITHUB_ENV

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/build/reports/tests/'
